github.com:
    users:
        OakyMacintosh:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: OakyMacintosh
